import Pieces from "./Pieces";

export const InitialGameStateRed = [
  [
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
  ],
  [
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
  ],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  [
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
  ],
  [
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
  ],
];

export const InitialGameStateBlue = [
  [
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
    Pieces.RED_BACK_ROW,
  ],
  [
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
    Pieces.RED_FRONT_ROW,
  ],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  [
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
    Pieces.BLUE_FRONT_ROW,
  ],
  [
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
    Pieces.BLUE_BACK_ROW,
  ],
];
