import Pieces from "./Pieces";

export const InitialGameStateWhite = [
  [
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
  ],
  [
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
  ],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  [
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
  ],
  [
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
  ],
];

export const InitialGameStateBlack = [
  [
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
    Pieces.WHITE_BACK_ROW,
  ],
  [
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
    Pieces.WHITE_FRONT_ROW,
  ],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  ["", "", "", "", "", ""],
  [
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
    Pieces.BLACK_FRONT_ROW,
  ],
  [
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
    Pieces.BLACK_BACK_ROW,
  ],
];
